version: "3.3"
services:
    proxy:
        container_name: nginx_proxy
        image: bitnami/nginx
        ports:
            - 50300:6543
        networks:
            - nginx-frontend-network
            - nginx-backend-network
            - nginx-mongo-client-network
        depends_on:
            - frontend
            - api
            - mongo
            - mongo-client
        volumes:
            - ./confs/my_server_block.conf:/opt/bitnami/nginx/conf/server_blocks/my_server_block.conf:ro
    frontend:
        container_name: frontend_lhs_prod
        build: 
            context: ./frontend
            target: prod # mudar para prod
        networks:
            - nginx-frontend-network
    api:
        container_name: API_lhs_prod
        build:
            context: ./backend
            target: prod
            args:
                port: ${BACKEND_PORT}
                ip: ${API_IP}
                swagger: ${SWAGGER_URL}
        environment:
            NODE_ENV: "prod"
        networks:
            - nginx-backend-network
    mongo:
        container_name: MongoDB_lhs_prod
    mongo-client:
        container_name: mongoclient_lhs_prod
        expose:
            - 8081
        volumes:
            - /data/db
        networks:
            - nginx-mongo-client-network
networks:
    nginx-frontend-network:
        driver: bridge
    nginx-backend-network:
        driver: bridge
    nginx-mongo-client-network:
        driver: bridge